---
name: Notify Home Assistant

# Secrets
# HAAS Webhook
#   http(s)://<your-hass-domain>/api/webhook/<webhook_id>

on:
  push:
    branches: [ '*' ]

jobs:
  deploy_config:
    runs-on: ubuntu-latest
    steps:
      - uses: joelwmale/webhook-action@2.2.0
        with:
          url: ${{ secrets.HASS_WEBHOOK_URL }}/update_config
          body: '{}'
